# Generated by Django 4.2.3 on 2023-08-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_create', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='article_images')),
            ],
        ),
    ]
