# Generated by Django 4.2.3 on 2023-09-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
