# Generated by Django 4.2.3 on 2023-09-13 19:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=tinymce.models.HTMLField(default='a'),
            preserve_default=False,
        ),
    ]
