# Generated by Django 4.2.3 on 2023-08-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('name_company', models.CharField(max_length=328)),
                ('review', models.TextField(blank=True)),
                ('rating', models.IntegerField()),
                ('is_publish', models.BooleanField(default=False)),
            ],
        ),
    ]
