# Generated by Django 4.2.3 on 2023-08-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
