# Generated by Django 4.2.3 on 2023-09-02 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0002_rename_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.file'),
        ),
    ]
