# Generated by Django 4.2.3 on 2023-09-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0004_alter_file_file_remove_problem_files_problem_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='problems',
            field=models.ManyToManyField(related_name='files', to='lawyer.problem'),
        ),
    ]
