# Generated by Django 4.2.3 on 2023-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0006_remove_file_problems_problem_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='problems',
            field=models.ManyToManyField(related_name='file_set', to='lawyer.problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='files',
            field=models.ManyToManyField(related_name='problem_set', to='lawyer.file'),
        ),
    ]
