# Generated by Django 4.2.3 on 2023-09-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0007_file_problems_alter_problem_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='problems',
        ),
        migrations.AlterField(
            model_name='problem',
            name='files',
            field=models.ManyToManyField(to='lawyer.file'),
        ),
    ]
