# Generated by Django 4.2.3 on 2023-09-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0008_remove_file_problems_alter_problem_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
