# Generated by Django 4.2.3 on 2023-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0009_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_lawyer'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
